if(TARGET_PLATFORM MATCHES "^ios-|^tvos-|^catalyst-")
  include(${CMAKE_CURRENT_LIST_DIR}/versions.apple.cmake)

  unset(PLATFORM)
  if(TARGET_PLATFORM STREQUAL ios-simx86)
    set(PLATFORM "SIMULATOR64")
  elseif(TARGET_PLATFORM STREQUAL ios-simarm64)
    set(PLATFORM "SIMULATORARM64")
  elseif(TARGET_PLATFORM MATCHES "^ios-arm")
    set(PLATFORM "OS")
    if(TARGET_PLATFORM STREQUAL ios-armv7)
      set(ARCHS "armv7")
    elseif(TARGET_PLATFORM STREQUAL ios-armv7s)
      set(ARCHS "armv7s")
    elseif(TARGET_PLATFORM STREQUAL ios-arm64)
      set(ARCHS "arm64")
    else()
      message(FATAL_ERROR "Unrecognized iOS target '${TARGET_PLATFORM}'")
    endif()
  endif()

  if(NOT PLATFORM)
    message(FATAL_ERROR "Target platform '${TARGET_PLATFORM}' unrecognized")
  endif()

  if(PLATFORM MATCHES "^OS|^SIMULATOR")
    set(DEPLOYMENT_TARGET ${IOS_MIN_VERSION})
  elseif(PLATFORM MATCHES "^MAC_CATALYST")
    set(DEPLOYMENT_TARGET ${MACOS_CATALYST_MIN_VERSION})
  elseif(PLATFORM MATCHES "^TVOS$")
    set(DEPLOYMENT_TARGET ${TVOS_MIN_VERSION})
  else()
    message(FATAL_ERROR "Platform '${PLATFORM}' not supported")
  endif()

  set(ENABLE_BITCODE OFF)
  set(ENABLE_ARC OFF)

  include(${CMAKE_CURRENT_LIST_DIR}/../external/ios-cmake/ios.toolchain.cmake)
endif()
